server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://my-postgres:5432/identity_service_db}
    driver-class-name: org.postgresql.Driver
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:bqtruong}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "y55jssnxso5ty90iwdxok7aampkd6aef50m66u0ryonpesec3q5senscnlg4m6sbq8pyjiypra3jv6mxmtvm8ju7orpe0tq8lkybghf1dhz1chtdbh08mn3nv19p3j97"
  valid-duration: 3600 # 60 seconds
  refreshable-duration: 36000 # 120 seconds