server:
  port: 8081
  servlet:
        context-path: /profile

spring:
  datasource:
    #    url: ${DBMS_CONNECTION:jdbc:postgresql://my-postgres:5432/identity_service_db}
    #     local
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/profile_service_db}
    driver-class-name: org.postgresql.Driver
    username: ${DBMS_USERNAME:postgres}
    #    password: ${DBMS_PASSWORD:bqtruong}
    # local
    password: ${DBMS_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
